### ISSUE TITLE
Problems with shortstack output interpretations 

### ISSUE THREAD

**Issue by RubioB** [MikeAxtell/ShortStack#102]
Hi !

I am a little confused concernaning the results obtained with shortstack. 

To sum up, I work with two conditions and in each of them I have three biological replicates. 

I firts performed an analysis under shortstack independently for each condition which allowad me to obtain the populations of smallRNA in each of the two conditions. In order to compare the populations of smallRNAs between my two conditions, I looked for the overlaps between clusters of the two analyzes (with bedIntersect). Thus, I identified 70% of clusters with overlap between the two conditions and so 30% clusters that were specific to each condition. 

At the same time,  I wanted to see if there were any expression differentials of smallRNA between my two conditions so I restarted an analysis under shortstack this time by analyzing the two conditions together. I then performed an analysis in DESEQ2 and it turned out that I only had a single cluster which was differentially expressed between my two conditions. 

Looking at the results obtained between the two analyses, I don't understand how I can find 'only' 70% of overlaps between my clusters whereas when performing analysis under DESEQ2 there is only one differentially expressed cluster ? 

Can you give me your opinion on these analyzes and results ? 
Maybe the are elements in my approach that are not right ? 

Thank you in advance for your reply !

Bernadette

**Comment by MikeAxtell** [comment]
Hi Bernadette, thanks for your question!

I think this is about what I would expect. Differential expression is a completely different protocol compared to ShortStack's cluster definition methods. Differential expression by DESeq2 makes a general linear model to approximate the within-condition variation, based on the biological reps. If the reps are noisy, and especially for lowly expressed clusters, you'll never get a significant diff exp. call.

On the other hand, ShortStack discovers clusters by a simple cutoff of peak abundance. Clusters that are inherently lowly expressed will likely be, at random, just above or just below the threshold in any given grouping of reads. In other words, just because 30% of the clusters weren't found in both conditions by ShortStack does not by itself prove with mathematical certainty that they are diff expressed.

BTW we usuall take a different approach: Take all libraries and do a single ShortStack run -  this defines a single set of sRNA clusters and should incorporate all of the data. Then use the counts in Counts.txt to run DESeq2.

Anyway hope this helps.

--
Michael J. Axtell, Ph.D.
Professor of Biology
Pennsylvania State University
https://sites.psu.edu/axtell
https://plantsmallrnagenes.science.psu.edu

**Comment by RubioB** [comment]
Your remarks confirm the assumptions I had !

Thank you very much for your answer !

Bernadette

________________________________
De : Mike Axtell <notifications@github.com>
Envoyé : lundi 2 novembre 2020 18:02
À : MikeAxtell/ShortStack <ShortStack@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [MikeAxtell/ShortStack] Problems with shortstack output interpretations (#102)


Hi Bernadette, thanks for your question!

I think this is about what I would expect. Differential expression is a completely different protocol compared to ShortStack's cluster definition methods. Differential expression by DESeq2 makes a general linear model to approximate the within-condition variation, based on the biological reps. If the reps are noisy, and especially for lowly expressed clusters, you'll never get a significant diff exp. call.

On the other hand, ShortStack discovers clusters by a simple cutoff of peak abundance. Clusters that are inherently lowly expressed will likely be, at random, just above or just below the threshold in any given grouping of reads. In other words, just because 30% of the clusters weren't found in both conditions by ShortStack does not by itself prove with mathematical certainty that they are diff expressed.

BTW we usuall take a different approach: Take all libraries and do a single ShortStack run - this defines a single set of sRNA clusters and should incorporate all of the data. Then use the counts in Counts.txt to run DESeq2.

Anyway hope this helps.

--
Michael J. Axtell, Ph.D.
Professor of Biology
Pennsylvania State University
https://sites.psu.edu/axtell
https://plantsmallrnagenes.science.psu.edu
