### ISSUE TITLE
FASTA format is unsupported for upgrade (4.0)

### ISSUE THREAD

**Issue by RJEGR** [MikeAxtell/ShortStack#114]
Hi Axtell,

This week I found the shortstack's upgrade (4.0). After the manual installation, I'm trying to identify known (`--knownRNAs`) in addition to de novo (`--dn_mirna`) miRs. I already have pre-processed libs, they are in fasta format - unsupported for released version of shortstack . It would be nice to allow the use of the fasta format again. I edited line 621-622  (`readfile_exts = ['.fasta', '.fa', '.fq', ...']`) and it seems to be working (I hope the downstream code does not crash 😅)

https://github.com/MikeAxtell/ShortStack/blob/d9b09e48b49ce4cb992898d1a3bcaf958d457f36/ShortStack#L621

Regards

**Comment by MikeAxtell** [comment]
Thanks Ricardo, I'll think on it. Hesitating because "pre-processed" can mean different things. For instance, if the "pre-processing" means that adapters are already trimmed, that's great. But, sometimes pre-processed might mean that people have collapsed thousands of identical sRNA sequences into a single FASTA entry, something like this:

```
>uniqueSeq 1256 reads
TACGACTAGGATAGCGATCAGCC
```
That would be bad because ShortStack operates on the premise that a single input read from a read file represents truly a single read, not a collapsed unique sequence entry.

Anyway, thanks for the suggestion. I'll keep it open and come back to it later .. right now working through the usual issues with a new major release.

**Comment by MikeAxtell** [comment]
Reconsidered and especially since the README claims that `--readfile` accepts fasta format, I guess I should make it so.

There were several other changes besides the lines you mentioned.

As of commit 3831aa7 this is fixed. It will be included along with some other bug fixes in the next release. If you want to use it immediately, you can download and install this commit (or any after it) manually.

**Comment by MikeAxtell** [comment]
Fix Included in release 4.0.1
