### ISSUE TITLE
SS 3.8.5 vs 4.0.1

### ISSUE THREAD

**Issue by kattri811** [MikeAxtell/ShortStack#135]
Hi Dr. Axtell,

I was previously using the SS 3.8.5 for our sRNA-seq data analysis and adapter-trimmed reads as input. Recently, I tried using SS 4.0.1 and using the trimmed reads as input gave an error in bowtie based alignments. In my understanding, the adapter trimming software I was using was leaving behind reads less than 12-nt and was causing issues in bowtie-based alignments. I then made use of the autotrim feature of the newest version and used raw files (with adapters) as input and the error was resolved. In this run, I do see a difference in the total number of loci detected for a miRNA family (say miR390): 4 loci were detected in SS 3.8.5 but 3 in SS 4.0.1. Could you provide some insights on if adapter-trimming is possibly making a difference or any other factors that I should be aware of?

Thanks,
Komal Attri

**Comment by MikeAxtell** [comment]
Differences in MIRNA calling between your experiments could be due to any one of the following:

- There are significant differences in the MIRNA-finding methods in version 4 and higher relative to version 3.x. Generally, 4 is "better" for various reasons.
- The same set of reads (even if trimmed exactly the same) won't make the same exact alignments. This is because the treatment of multi-mapped reads is heuristic. See Johnson et al. (2016) 10.1534/g3.116.030452
- Differences in adapter trimming might make a difference too, but I suspect the larger effects are the other two points I mention above.

From: kattri811 ***@***.***>
Date: Thursday, June 29, 2023 at 1:15 PM
To: MikeAxtell/ShortStack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MikeAxtell/ShortStack] SS 3.8.5 vs 4.0.1 (Issue #135)

Hi Dr. Axtell,

I was previously using the SS 3.8.5 for our sRNA-seq data and adapter-trimmed reads as input. Recently, I tried using SS 4.0.1 and using the trimmed reads as input gave an error in bowtie based alignments. In my understanding, the adapter trimming software I was using was leaving behind reads less than 12-nt and was causing issues in bowtie-based alignments. I then made use of the autotrim feature of the newest version and used raw files (with adapters) as input and the error was resolved. In this run, I do see a difference in the total number of loci detected for a miRNA family (say miR390): 4 loci were detected in SS 3.8.5 but 3 in SS 4.0.1. Could you provide some insights on if adapter-trimming is possibly making a difference or any other factors that I should be aware of?

Thanks,
Komal Attri

**Comment by kattri811** [comment]
Dr. Axtell,
Thanks for your response.
