### ISSUE TITLE
FATAL: bowtie encountered an error!

### ISSUE THREAD

**Issue by Simson896** [MikeAxtell/ShortStack#158]
Hi Mike, 

I am new to bioinformatics and would like to analyse smallRNA Seq data using ShortStack. 

I have downloaded the test data set to get started and would like to analyse it. I am getting the following error: 

(base) Test % ShortStack --genomefile Arabidopsis_thalianaTAIR10.fa --readfile SRR3222443.fastq SRR3222444.fastq SRR3222445.fastq --autotrim --threads 6 --outdir ExampleShortStackRun --known_miRNAs ath_known_miRNAs.fasta

ShortStack version 4.0.4

Beginning run
Options:
{   'adapter': None,
    'align_only': False,
    'autotrim': True,
    'autotrim_key': 'TCGGACCAGGCTTCATTCCCC',
    'bamfile': None,
    'dicermax': 24,
    'dicermin': 21,
    'dn_mirna': False,
    'genomefile': 'Arabidopsis_thalianaTAIR10.fa',
    'known_miRNAs': 'ath_known_miRNAs.fasta',
    'locifile': None,
    'locus': None,
    'mincov': 1,
    'mmap': 'u',
    'no_bigwigs': False,
    'nohp': False,
    'outdir': 'ExampleShortStackRun',
    'pad': 200,
    'readfile': ['SRR3222443.fastq', 'SRR3222444.fastq', 'SRR3222445.fastq'],
    'show_secondaries': False,
    'strand_cutoff': 0.8,
    'threads': 6}
Required executable RNAfold : /Users/xxxx/anaconda3/bin/RNAfold
Required executable strucVis : /Users/xxxx/anaconda3/bin/strucVis
Required executable bowtie : /Users/xxxx/anaconda3/bin/bowtie
Required executable bowtie-build : /Users/xxxx/anaconda3/bin/bowtie-build
Required executable ShortTracks : /Users/xxxx/anaconda3/bin/ShortTracks
Required executable wigToBigWig : /Users/xxxx/anaconda3/bin/wigToBigWig
Required executable cutadapt : /Users/xxxx/anaconda3/bin/cutadapt
Required executable samtools : /Users/xxxx/anaconda3/bin/samtools
Mon 12 Aug 2024 15:12:14 +0200 CEST

Initiating autotrim with an autotrim_key of TCGGACCAGGCTTCATTCCCC

Adapters:                                                 
[('SRR3222443.fastq', 'TGGAATTCTCGGGTGCCAAG'),            
 ('SRR3222444.fastq', 'TGGAATTCTCGGGTGCCAAG'),             
 ('SRR3222445.fastq', 'TGGAATTCTCGGGTGCCAAG')]

Mon 12 Aug 2024 15:12:51 +0200 CEST
Initiating read trimming with cutadapt

Trimming readfile SRR3222443.fastq ...
Done           00:00:24     7,641,498 reads @   3.2 µs/read;  18.97 M reads/minute
status	in_reads	in_bp	too_short	too_long	too_many_n	out_reads	w/adapters	qualtrim_bp	out_bp
OK	7641498	382074900	568519	0	0	6964746	7533265	0	160030151
  Completed. Trimmed file is ExampleShortStackRun/tSRR3222443.fastq.

Trimming readfile SRR3222444.fastq ...
Done           00:00:28     9,366,086 reads @   3.0 µs/read;  19.97 M reads/minute
status	in_reads	in_bp	too_short	too_long	too_many_n	out_reads	w/adapters	qualtrim_bp	out_bp
OK	9366086	468304300	812135	0	0	8232387	9044522	0	193110300
  Completed. Trimmed file is ExampleShortStackRun/tSRR3222444.fastq.

Trimming readfile SRR3222445.fastq ...
Done           00:00:38    12,937,592 reads @   3.0 µs/read;  20.05 M reads/minute
status	in_reads	in_bp	too_short	too_long	too_many_n	out_reads	w/adapters	qualtrim_bp	out_bp
OK	12937592	646879600	1229445	0	0	11602752	12832197	0	268799716
  Completed. Trimmed file is ExampleShortStackRun/tSRR3222445.fastq.

Mon 12 Aug 2024 15:14:23 +0200 CEST
Required bowtie indices not found. Building them ...

    Completed

Beginning alignment phase

Mon 12 Aug 2024 15:16:23 +0200 CEST
Aligning ExampleShortStackRun/tSRR3222443.fastq
First pass alignment with bowtie using 6 threads
0 bowtie output lines [00:00, ? bowtie output lines/s]
FATAL: bowtie encountered an error!

The automatically generated index files seem to be correct, as I can process them without error by manually running bowtie alignment. All files are in the right folder. 

I am using Python 3.10.14, ShortStack 4.0.4 and bowtie 1.3.1

Do you have any explanation for this error? 

Many thanks in advance
Simon

**Comment by MikeAxtell** [comment]
Hello Simon,

I don't know what the issue is here. Command looks fine. I noticed your executables are being managed by anaconda3 instead of the recommended miniconda. I wonder if there is something strange going on with the use of anaconda3?

The error is a generic one which ShortStack triggers if a bowtie call returns a non-zero exit code (see line 1063). You could edit the script to try and see what exact error message bowtie is reporting in this condition.

I don't know of any incompatibilities with the software versions you are using. My test environment uses the same versions as you. I confirmed just now that the test set works on my system.

I would try scrubbing out your Anaconda installation and instead use the recommended miniconda / bioconda method of installing the dependencies. Anaconda IMHO is bloated and in my experience that bloat can do strange things.

- Mike


From: Simson896 ***@***.***>
Date: Monday, August 12, 2024 at 9:21 AM
To: MikeAxtell/ShortStack ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MikeAxtell/ShortStack] FATAL: bowtie encountered an error! (Issue #158)

Hi Mike,

I am new to bioinformatics and would like to analyse smallRNA Seq data using ShortStack.

I have downloaded the test data set to get started and would like to analyse it. I am getting the following error:

(base) Test % ShortStack --genomefile Arabidopsis_thalianaTAIR10.fa --readfile SRR3222443.fastq SRR3222444.fastq SRR3222445.fastq --autotrim --threads 6 --outdir ExampleShortStackRun --known_miRNAs ath_known_miRNAs.fasta

ShortStack version 4.0.4

Beginning run
Options:
{ 'adapter': None,
'align_only': False,
'autotrim': True,
'autotrim_key': 'TCGGACCAGGCTTCATTCCCC',
'bamfile': None,
'dicermax': 24,
'dicermin': 21,
'dn_mirna': False,
'genomefile': 'Arabidopsis_thalianaTAIR10.fa',
'known_miRNAs': 'ath_known_miRNAs.fasta',
'locifile': None,
'locus': None,
'mincov': 1,
'mmap': 'u',
'no_bigwigs': False,
'nohp': False,
'outdir': 'ExampleShortStackRun',
'pad': 200,
'readfile': ['SRR3222443.fastq', 'SRR3222444.fastq', 'SRR3222445.fastq'],
'show_secondaries': False,
'strand_cutoff': 0.8,
'threads': 6}
Required executable RNAfold : /Users/xxxx/anaconda3/bin/RNAfold
Required executable strucVis : /Users/xxxx/anaconda3/bin/strucVis
Required executable bowtie : /Users/xxxx/anaconda3/bin/bowtie
Required executable bowtie-build : /Users/xxxx/anaconda3/bin/bowtie-build
Required executable ShortTracks : /Users/xxxx/anaconda3/bin/ShortTracks
Required executable wigToBigWig : /Users/xxxx/anaconda3/bin/wigToBigWig
Required executable cutadapt : /Users/xxxx/anaconda3/bin/cutadapt
Required executable samtools : /Users/xxxx/anaconda3/bin/samtools
Mon 12 Aug 2024 15:12:14 +0200 CEST

Initiating autotrim with an autotrim_key of TCGGACCAGGCTTCATTCCCC

Adapters:
[('SRR3222443.fastq', 'TGGAATTCTCGGGTGCCAAG'),
('SRR3222444.fastq', 'TGGAATTCTCGGGTGCCAAG'),
('SRR3222445.fastq', 'TGGAATTCTCGGGTGCCAAG')]

Mon 12 Aug 2024 15:12:51 +0200 CEST
Initiating read trimming with cutadapt

Trimming readfile SRR3222443.fastq ...
Done 00:00:24 7,641,498 reads @ 3.2 µs/read; 18.97 M reads/minute
status in_reads in_bp too_short too_long too_many_n out_reads w/adapters qualtrim_bp out_bp
OK 7641498 382074900 568519 0 0 6964746 7533265 0 160030151
Completed. Trimmed file is ExampleShortStackRun/tSRR3222443.fastq.

Trimming readfile SRR3222444.fastq ...
Done 00:00:28 9,366,086 reads @ 3.0 µs/read; 19.97 M reads/minute
status in_reads in_bp too_short too_long too_many_n out_reads w/adapters qualtrim_bp out_bp
OK 9366086 468304300 812135 0 0 8232387 9044522 0 193110300
Completed. Trimmed file is ExampleShortStackRun/tSRR3222444.fastq.

Trimming readfile SRR3222445.fastq ...
Done 00:00:38 12,937,592 reads @ 3.0 µs/read; 20.05 M reads/minute
status in_reads in_bp too_short too_long too_many_n out_reads w/adapters qualtrim_bp out_bp
OK 12937592 646879600 1229445 0 0 11602752 12832197 0 268799716
Completed. Trimmed file is ExampleShortStackRun/tSRR3222445.fastq.

Mon 12 Aug 2024 15:14:23 +0200 CEST
Required bowtie indices not found. Building them ...

Completed

Beginning alignment phase

Mon 12 Aug 2024 15:16:23 +0200 CEST
Aligning ExampleShortStackRun/tSRR3222443.fastq
First pass alignment with bowtie using 6 threads
0 bowtie output lines [00:00, ? bowtie output lines/s]
FATAL: bowtie encountered an error!

The automatically generated index files seem to be correct, as I can process them without error by manually running bowtie alignment. All files are in the right folder.

I am using Python 3.10.14, ShortStack 4.0.4 and bowtie 1.3.1

Do you have any explanation for this error?

Many thanks in advance
Simon
