### ISSUE TITLE
Is Shortstack sensitive to detect small RNAs that do not exist in reference genome

### ISSUE THREAD

**Issue by xingwu2** [MikeAxtell/ShortStack#29]
Hi MIke:

I am working on soybean small RNAseq data. The genome of soybean line I sequenced is different from the reference genome( William 82). Two soybean genomes have high similarity, but i am looking for a novel small RNA (na-siRNA specifically) which accounts for a trait difference. 

Is shortstack sensitive enough to detect the na-si RNA that do not exist in the reference genome? If so, how can I extract the real cluster sequences.  

Best

Xing

**Comment by MikeAxtell** [comment]
Hi Xing,
ShortStack relies upon reference-aligned small RNA-seq data. If your RNA of interest is not alignable to the reference genome, then ShortStack won't find it. You can set the --mismatches option to 2 (instead of the default 1) to maximize alignment sensitivity to account for SNPs between your sample and the reference genome. If it's more than two mismatches, ShortStack will never align it.

Hope that helps,
Mike
