### ISSUE TITLE
Discrepancy between MeanReads and Reads

### ISSUE THREAD

**Issue by MikeAxtell** [MikeAxtell/ShortStack#46]
Noticed in version 3.6 (but probably earlier versions as well) that Reads is very frequently much higher than MeanReads + StdevReads. Possibly different treatments of edge-touching reads; in any case it's a bug.

**Comment by rmonti** [comment]
Hi Mike,

I've noticed this too, but I figured it was when there were relatively few uniquely mapping reads. it might be that there's another locus with the same MajorRNA with way more reads, because there are more uniquely mapping reads there. 

This might be completely wrong, but it's worth checking

**Comment by MikeAxtell** [comment]
Fixed in release 3.7
