### ISSUE TITLE
differential gene expression

### ISSUE THREAD

**Issue by mustafaraza1987** [MikeAxtell/ShortStack#87]
Hello Dear Sir,
Can you please explain about the analysis of  differential gene expression of miRNA (replicate data) with short stack. I already mine miRNA from different replicates, but now issues is that how to create count matrix from count data as well as rpm , Each replicates provide the clusters different in number. Suppose replicate_1 =500 ,replicate_2=200, replicate_3=100. How to create count matrix in such a way  .

**Comment by groverj3** [comment]
I'm not Mike, but I think it sounds like you've run ShortStack on all your libraries independently. If you do that, it only uses that particular replicate's reads to generate loci. In order to have loci that are defined with all your samples, such that every sample has the same number of loci defined, with a value in the counts.txt file you just need to run them all together.

So, either provide all the .fastq files to ShortStack at once, or map them all separately and use samtools merge to generate a single .bam file to feed into ShortStack to define loci.
